---
apiVersion: apps/v1 #beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-world
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kms-hello-world
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: kms-hello-world
    spec:
      containers:
      - name: kurento-hello-world
        image: nordri/kurento-hello-world:no-ssldcnljfnvlkvf
        env:
        - name: "KMS_URL"
          value: "kms-service"
        - name: "KMS_PORT"
          value: "8888"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: kms-hello-world
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: hello-world-port
  selector:
    app: kms-hello-world
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: hello-world-ingress
    annotations:
      kubernetes.io/tls-acme: 'true'
      kubernetes.io/ingress.class: nginx
    labels:
      app: kurento-hello-world
spec:
  rules:
  - host: hello-world.openvidu.io
    http:
      paths:
      - backend:
          serviceName: hello-world-service
          servicePort: 8080
  tls:
  - secretName: hello-world-secret
    hosts:
    - hello-world.openvidu.io
